### ISSUE TITLE
ArgumentError: config.secret_token

### ISSUE THREAD

**Issue by sparknlaunch** [8bitpal/hackful#56]
When running get the below three errors. The third error displays when loading localhost:3000. What step is required to resole?

[DEVISE] Devise.apply_schema is deprecated and has no effect. Please remove it.

[DEVISE] Devise.use_salt_as_remember_token is deprecated and has no effect. Please remove it.

ArgumentError (A secret is required to generate an integrity hash for cookie session data. Use config.secret_token = "some secret phrase of at least 30 characters"in config/initializers/secret_token.rb):

**Comment by 8bitpal** [comment]
I'm sorry, this COMPLETELY slipped under my radar. You have probably solved this. 
I took out the file config/initializers/secret_token.rb because, as the name hints at, it contains the secret token. S

Please create the file and add:

"Hackful::Application.config.secret_token = 'RANDOMSTRINGSHOULDBEQUITELONG' "
